"""TKT-4F estimate options templates documents and delivery."""
from alembic import op
import sqlalchemy as sa

revision="20260807_16"
down_revision="20260807_15"
branch_labels=None
depends_on=None

def upgrade() -> None:
    op.create_table("estimate_options",
        sa.Column("id",sa.Integer(),primary_key=True),sa.Column("estimate_id",sa.Integer(),sa.ForeignKey("estimates.id",ondelete="CASCADE"),nullable=False),sa.Column("name",sa.String(160),nullable=False),sa.Column("customer_notes",sa.Text(),nullable=False,server_default=""),sa.Column("sort_order",sa.Integer(),nullable=False,server_default="0"),sa.Column("subtotal",sa.Numeric(14,2),nullable=False,server_default="0"),sa.Column("discount_total",sa.Numeric(14,2),nullable=False,server_default="0"),sa.Column("taxable_subtotal",sa.Numeric(14,2),nullable=False,server_default="0"),sa.Column("tax_total",sa.Numeric(14,2),nullable=False,server_default="0"),sa.Column("total",sa.Numeric(14,2),nullable=False,server_default="0"),sa.Column("estimated_cost",sa.Numeric(14,2),nullable=False,server_default="0"),sa.Column("gross_profit",sa.Numeric(14,2),nullable=False,server_default="0"),sa.Column("margin_percent",sa.Numeric(8,2),nullable=False,server_default="0"),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()))
    op.create_index("ix_est_option_estimate","estimate_options",["estimate_id"])
    op.add_column("estimate_line_items",sa.Column("option_id",sa.Integer(),nullable=True))
    op.execute(sa.text("INSERT INTO estimate_options (estimate_id,name,customer_notes,sort_order,subtotal,discount_total,taxable_subtotal,tax_total,total,estimated_cost,gross_profit,margin_percent,created_at,updated_at) SELECT id,'Estimate',customer_notes,1,subtotal,discount_total,taxable_subtotal,tax_total,total,estimated_cost,gross_profit,margin_percent,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM estimates"))
    op.execute(sa.text("UPDATE estimate_line_items line SET option_id=opt.id FROM estimate_options opt WHERE opt.estimate_id=line.estimate_id"))
    op.alter_column("estimate_line_items","option_id",existing_type=sa.Integer(),nullable=False)
    op.create_foreign_key("fk_est_line_option","estimate_line_items","estimate_options",["option_id"],["id"],ondelete="CASCADE"); op.create_index("ix_est_line_option","estimate_line_items",["option_id"])
    op.create_table("estimate_email_templates",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("organization_id",sa.Integer(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("name",sa.String(160),nullable=False),sa.Column("subject_template",sa.String(300),nullable=False),sa.Column("body_template",sa.Text(),nullable=False),sa.Column("active",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("created_by_user_id",sa.Integer(),sa.ForeignKey("users.id",ondelete="SET NULL"),nullable=True),sa.Column("updated_by_user_id",sa.Integer(),sa.ForeignKey("users.id",ondelete="SET NULL"),nullable=True),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.UniqueConstraint("organization_id","name",name="uq_est_email_template_org_name"))
    op.create_index("ix_est_email_template_org","estimate_email_templates",["organization_id"]); op.create_index("ix_est_email_template_active","estimate_email_templates",["active"])
    op.execute(sa.text("INSERT INTO estimate_email_templates (organization_id,name,subject_template,body_template,active,created_at,updated_at) SELECT DISTINCT organization_id,'Standard Estimate','Sales Proposal from NTInet for {{customer_name}}','{{contact_name}},\n\nThank you for giving NTInet an opportunity to take care of your service needs.\n\nAttached is proposal {{estimate_number}} for {{estimate_title}}.\n\nSelected options: {{option_names}}\n\nShould you have questions, please contact us.\n\n{{sender_name}}',TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM estimates"))
    op.create_table("stored_documents",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("organization_id",sa.Integer(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("name",sa.String(200),nullable=False),sa.Column("description",sa.Text(),nullable=False,server_default=""),sa.Column("original_filename",sa.String(255),nullable=False),sa.Column("stored_filename",sa.String(255),nullable=False,unique=True),sa.Column("content_type",sa.String(120),nullable=False,server_default="application/octet-stream"),sa.Column("size_bytes",sa.Integer(),nullable=False,server_default="0"),sa.Column("active",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("uploaded_by_user_id",sa.Integer(),sa.ForeignKey("users.id",ondelete="SET NULL"),nullable=True),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()))
    op.create_index("ix_stored_doc_org","stored_documents",["organization_id"]); op.create_index("ix_stored_doc_name","stored_documents",["name"]); op.create_index("ix_stored_doc_active","stored_documents",["active"]); op.create_index("ix_stored_doc_created","stored_documents",["created_at"])
    op.create_table("estimate_documents",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("estimate_id",sa.Integer(),sa.ForeignKey("estimates.id",ondelete="CASCADE"),nullable=False),sa.Column("document_id",sa.Integer(),sa.ForeignKey("stored_documents.id",ondelete="CASCADE"),nullable=False),sa.Column("attached_by_user_id",sa.Integer(),sa.ForeignKey("users.id",ondelete="SET NULL"),nullable=True),sa.Column("attached_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.UniqueConstraint("estimate_id","document_id",name="uq_estimate_document"))
    op.create_index("ix_est_doc_estimate","estimate_documents",["estimate_id"]); op.create_index("ix_est_doc_document","estimate_documents",["document_id"])
    op.create_table("estimate_deliveries",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("estimate_id",sa.Integer(),sa.ForeignKey("estimates.id",ondelete="CASCADE"),nullable=False),sa.Column("contact_id",sa.Integer(),sa.ForeignKey("customer_contacts.id",ondelete="SET NULL"),nullable=True),sa.Column("recipient_email",sa.String(255),nullable=False),sa.Column("subject",sa.String(300),nullable=False),sa.Column("message_body",sa.Text(),nullable=False),sa.Column("option_ids_json",sa.Text(),nullable=False,server_default="[]"),sa.Column("document_ids_json",sa.Text(),nullable=False,server_default="[]"),sa.Column("pdf_attached",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("status",sa.String(20),nullable=False),sa.Column("error_message",sa.Text(),nullable=False,server_default=""),sa.Column("sent_by_user_id",sa.Integer(),sa.ForeignKey("users.id",ondelete="SET NULL"),nullable=True),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()))
    for name,col in (("ix_est_delivery_estimate","estimate_id"),("ix_est_delivery_contact","contact_id"),("ix_est_delivery_status","status"),("ix_est_delivery_created","created_at")): op.create_index(name,"estimate_deliveries",[col])

def downgrade() -> None:
    op.drop_table("estimate_deliveries"); op.drop_table("estimate_documents"); op.drop_table("stored_documents"); op.drop_table("estimate_email_templates")
    op.drop_index("ix_est_line_option",table_name="estimate_line_items"); op.drop_constraint("fk_est_line_option","estimate_line_items",type_="foreignkey"); op.drop_column("estimate_line_items","option_id"); op.drop_table("estimate_options")
